; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.26"

; Modules
projects[views_bulk_operations][version] = "3.1"

projects[admin_menu][version] = "3.0-rc4"

projects[afb][version] = "1.0"

projects[auto_entitylabel][version] = "1.2"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.7"

projects[backup_migrate_files][subdir] = "contrib"
projects[backup_migrate_files][version] = "1.x-dev"

projects[better_exposed_filters][version] = "3.0-beta3"

projects[better_formats][version] = "1.0-beta1"

projects[block_class][version] = "2.0"

projects[block_titlelink][version] = "1.3"

projects[boost][subdir] = "contrib"
projects[boost][version] = "1.0"

projects[ctools][version] = "1.4"

projects[bundle_inherit][version] = "1.0-alpha2"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.0+4-dev"

projects[compact_forms][version] = "1.0"

projects[conditional_fields][version] = "3.x-dev"

projects[context][version] = "3.2"

projects[cryptolog][subdir] = "contrib"
projects[cryptolog][version] = "1.2"

projects[custom_formatters][version] = "2.2"

projects[date][version] = "2.6"

projects[deploy][version] = "2.0-alpha1"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[email_registration][version] = "1.1"

projects[entity][version] = "1.3"

projects[entity_dependency][version] = "1.0-alpha1"

projects[entity_translation][version] = "1.0-beta3"

projects[entity_view_mode][version] = "1.0-rc1"

projects[entityreference][version] = "1.1"

projects[eva][version] = "1.2"

projects[exclude_node_title][version] = "1.6"

projects[expire][subdir] = "contrib"
projects[expire][version] = "2.0-rc3+1-dev"

projects[fast_404][subdir] = "contrib"
projects[fast_404][version] = "1.3"

projects[features_extra][version] = "1.0-beta1"

projects[features][version] = "2.0"

projects[features_translations][subdir] = "contrib"
projects[features_translations][version] = "1.0-beta4"

projects[field_collection][version] = "1.0-beta5"

projects[field_group][version] = "1.1"

projects[field_permissions][version] = "1.0-beta2"

projects[field_tools][version] = "1.0-alpha3"

projects[filefield_sources][version] = "1.9"

projects[formblock][version] = "1.x-dev"

projects[fpa][version] = "2.3"

projects[get_form_id][version] = "1.0"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5+3-dev"

projects[honeypot][subdir] = "contrib"
projects[honeypot][version] = "1.17"

projects[httprl][subdir] = "contrib"
projects[httprl][version] = "1.14"

projects[i18n][version] = "1.11"

projects[i18nviews][subdir] = "contrib"
projects[i18nviews][version] = "3.x-dev"

projects[inline_entity_form][version] = "1.2"

projects[insert][subdir] = "contrib"
projects[insert][version] = "1.3"

projects[interval][version] = "1.0-rc1"

projects[jquery_update][version] = "2.3"

projects[l10n_update][version] = "1.0-beta3"

projects[less][subdir] = "contrib"
projects[less][version] = "3.0"

projects[libraries][version] = "2.1"

projects[link][version] = "1.1"

projects[markdown][subdir] = "contrib"
projects[markdown][version] = "1.2"

projects[masquerade][version] = "1.0-rc7"

projects[navigation404][subdir] = "contrib"
projects[navigation404][version] = "1.0"

projects[oauth][subdir] = "contrib"
projects[oauth][version] = "3.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[openintegrity][download][type] = ""
projects[openintegrity][download][url] = ""
projects[openintegrity][type] = "module"
projects[openintegrity][version] = "1.0-alpha1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[openintegrity_helper][download][type] = ""
projects[openintegrity_helper][download][url] = ""
projects[openintegrity_helper][type] = "module"
projects[openintegrity_helper][subdir] = "openintegrity"
projects[openintegrity_helper][version] = "1.0-alpha1"

projects[password_policy][subdir] = "contrib"
projects[password_policy][version] = "2.0-alpha3+11-dev"

projects[password_tab][subdir] = "contrib"
projects[password_tab][version] = "1.x-dev"

projects[prlp][subdir] = "contrib"
projects[prlp][version] = "1.0-beta2"

projects[profile2][subdir] = "contrib"
projects[profile2][version] = "1.3+5-dev"

projects[profile2_regpath][subdir] = "contrib"
projects[profile2_regpath][version] = "2.0-beta3+12-dev"

projects[services][subdir] = "contrib"
projects[services][version] = "3.7"

projects[revisioning][version] = "1.8"

projects[riddler][subdir] = "contrib"
projects[riddler][version] = "1.2"

projects[rules][version] = "2.3"

projects[search_api][version] = "1.6"

projects[search_api_autocomplete][version] = "1.0"

projects[search_api_db][version] = "1.0-rc1"

projects[search_api_solr][subdir] = "contrib"
projects[search_api_solr][version] = "1.2"

projects[security_check][version] = "1.0-beta1"

projects[security_review][version] = "1.0"

projects[services_views][subdir] = "contrib"
projects[services_views][version] = "1.0+4-dev"

projects[simplehtmldom][version] = "1.12"

projects[strongarm][version] = "2.0"

projects[submitted_by][version] = "1.x-dev"

projects[tablefield][version] = "2.1"

projects[taxonomy_manager][version] = "1.0"

projects[term_reference_tree][subdir] = "contrib"
projects[term_reference_tree][version] = "1.10+0-dev"

projects[textformatter][version] = "1.3"

projects[title][subdir] = "contrib"
projects[title][version] = "1.0-alpha7"

projects[tmgmt][version] = "1.0-beta2"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[user_verify][subdir] = "contrib"
projects[user_verify][version] = "2.0-alpha1+1-dev"

projects[uuid][version] = "1.0-alpha5"

projects[uuid_features][version] = "1.0-alpha3"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[view_mode_page][subdir] = "contrib"
projects[view_mode_page][version] = "2.2"

projects[views][version] = "3.7"
projects[views][patches][0] = "https://drupal.org/files/views-grouping-level-always-is-zero-1488744-3_0.patch"
projects[views][patches][1] = "https://drupal.org/files/views-grouping-level-always-is-zero-1488744-3_0.patch"

projects[views404][subdir] = "contrib"
projects[views404][version] = "1.x-dev"

projects[views_accordion][version] = "1.0-rc2"

projects[views_block_area][version] = "1.1"

projects[views_content_cache][version] = "3.0-alpha2"

projects[views_field_view][version] = "1.1"

projects[views_datasource][subdir] = "contrib"
projects[views_datasource][version] = "1.x-dev"

projects[views_php][version] = "1.x-dev"

projects[views_rules][version] = "1.0"

projects[views_tree][version] = "2.0"

; Themes
projects[bootstrap][version] = "2.1"

; Modules
projects[potx][type] = "module"
projects[potx][download][type] = "git"
projects[potx][download][url] = "http://git.drupal.org/project/potx.git"
projects[potx][download][branch] = "720986-drush-integration-34"
projects[potx][download][revision] = "2a50dacfab0afd1ee79f8b675c274520378afaee"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = ""
libraries[lessphp][download][url] = ""
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[editarea][download][type] = ""
libraries[editarea][download][url] = ""
libraries[editarea][directory_name] = "editarea"
libraries[editarea][type] = "library"

